name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: npm install

      - name: Execute CI/CD Process
        run: npm run CICD
